name: cpd
channels:
  - conda-forge
  - defaults
  
dependencies:
  - python=3.8
  - pygmt
  - matplotlib=3.4.2
  - osgeo=3.3.1
  - pandas
  - pip
  - pip:
    - statsmodels
    - git+https://github.com/jobar8/graphics.git 
    - git+https://github.com/craigmillernz/cm_utils.git
