name: cpd
channels:
  - defaults
  
dependencies:
  - python=3.8
  - pygmt
  - matplotlib
  - pandas
  - scikit-image
  - pyshp
  - cmcrameri
  - xarray
  - pip
  - pip:
    - statsmodels
    - gdal
  
